name: phyzzicare

description: A project for provide an app for specifically stroke as well as for other service

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  faker: ^2.1.0
  chips_choice: ^3.0.0
  shared_preferences: ^2.1.0
  buttons_tabbar: ^1.3.6
  flutter_swipe_button: ^2.1.1+1
  fluttertoast: ^8.2.2
  objectbox: ^2.1.0
  objectbox_flutter_libs: any
  path: 1.8.3
  path_provider: 2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  objectbox_generator: any
  
flutter:
  uses-material-design: true

  assets:
    - assets/
    - icons/
    - lib/generated/
    - lib/generated/assets.dart