name: phyzzicare

description: A project for provide an app for specifically stroke as well as for other service

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  faker: ^2.1.0
  chips_choice: ^3.0.0
  shared_preferences: ^2.1.0
  loop_page_view: ^1.2.1
  smooth_page_indicator: ^1.1.0
  buttons_tabbar: ^1.3.6
  lite_rolling_switch: ^1.0.1
  badges: ^3.1.1
  flutter_swipe_button: ^2.1.1+1
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - icons/